version: '3.8'

services:
  db:
    image: mysql:8.0.26
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80 #daphne -b 0.0.0.0 -p 80 dating.asgi:application
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_HOST: db
      MYSQL_NAME: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      REDIS_HOST: redis
      REDIS_PORT: 6379
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025" # Web interface
  #     - "1025:1025" # SMTP server

volumes:
  redis:
  mysql:
