version: '3.8'

services:
  db:
    image: mysql:8.0.26
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_NAME: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web interface
      - "1025:1025" # SMTP server

volumes:
  mysql:
